<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
            margin: 0;
            padding: 20px;
        }

        .container {
            width: 100%;
            /* max-width: 800px; */
            margin: 0 auto;
            background-color: white;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #2c3e50;
            font-size: 28px;
            text-align: center;
            margin-bottom: 20px;
            padding: 2rem;
        }

        .reference-card {
            /* background-color: #ecf0f1; */
            padding: 20px;
            border-radius: 8px;
            /* box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); */
            margin-bottom: 30px;
        }

        .reference-number {
            font-size: 24px;
            font-weight: bold;
            color: #00aeff;
            text-align: center;
            margin-top: 10px;
            padding: 10px;
            background-color: #ffffff;
            border: 2px solid #00aeff;
            border-radius: 8px;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            color: #7f8c8d;
            margin-top: 20px;
        }

        .info {
            font-size: 16px;
            color: #34495e;
            line-height: 1.6;
            margin-bottom: 20px;
            padding: 2rem;
        }

        .info strong {
            font-weight: bold;
            color: #2c3e50;
        }

        .highlight {
            color: #3498db;
            font-weight: bold;
        }
    </style>
    <title>Reference Number Document</title>
</head>
<body>
    <div class="container">
        <h1>Reference Number</h1>

        <div class="info">
            <p><strong>Dear {{ $userName }},</strong></p>
            <p>We appreciate your patience. Your case has been processed, and the reference number has been assigned to you. Below are the details:</p>
        </div>

        <!-- Reference Card -->
        <div class="reference-card">
            <div class="reference-number">
                {{ $referenceNumber }}
            </div>
        </div>

        <div class="info">
            <p><strong>Case Status:</strong> {{ $caseStatus }}</p>
            <p><strong>Date Processed:</strong> {{ $dateProcessed }}</p>
        </div>

        <div class="footer">
            <p>Generated by REPUBLIC OF THE PHILIPPINES COMMISION ON HUMAN RIGHTS | {{ date('Y') }}</p>
        </div>
    </div>
</body>
</html>
